<?php

declare(strict_types=1);

/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yiiunit\framework\log\mocks;

use yii\log\Target;

class TargetMock extends Target
{
    public $collectOverride;

    /**
     * {@inheritDoc}
     */
    public function export(): void
    {
    }

    public function collect($messages, $final): void
    {
        if ($this->collectOverride !== null) {
            call_user_func($this->collectOverride, $messages, $final);

            return;
        }
        parent::collect($messages, $final); // TODO: Change the autogenerated stub
    }
}
