name: ci-mssql

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  COMPOSER_INSTALL_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} mssql ${{ matrix.mssql-version }} on ${{ matrix.os-version }}

    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - ubuntu-20.04
          - ubuntu-22.04

        php-version:
          - "8.0"
          - "8.1"
          - "8.2"

        mssql-version:
          - "2019-latest"

    services:
      mssql:
          image: mcr.microsoft.com/mssql/server:${{ matrix.mssql-version }}
          env:
              SA_PASSWORD: YourStrong!Passw0rd
              ACCEPT_EULA: Y
              MSSQL_PID: Developer
          ports:
              - 1433:1433
          options: --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create MSSQL Database
        run: docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite, pdo_sqlsrv
          ini-values: date.timezone='UTC'

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer install $COMPOSER_INSTALL_FLAGS

      - name: PHPUnit
        run: vendor/bin/phpunit --group mssql --colors=always
