name: ci-mysql

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  COMPOSER_INSTALL_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} mysql ${{ matrix.mysql-version }} on ${{ matrix.os-version }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - ubuntu-latest

        php-version:
          - "8.0"
          - "8.1"

        mysql-version:
          - "5.7"
          - "8.0"

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite
          ini-values: date.timezone='UTC'

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer install $COMPOSER_INSTALL_FLAGS

      - name: PHPUnit
        run: vendor/bin/phpunit --group mysql --colors=always
