name: ci-pgsql

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} pgsql ${{ matrix.pgsql-version }} on ${{ matrix.os-version }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      extensions: curl, intl, pdo, pdo_pgsql

    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - ubuntu-latest

        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

        pgsql-version:
          - "14"

    services:
      postgres:
        image: postgres:${{ matrix.pgsql-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: PHPUnit
        run: vendor/bin/phpunit --group pgsql --colors=always
