name: ci-pgsql

on:
  pull_request:
    branches:
      - master

  schedule:
    # every day at 1:15 and 12:15 UTC
    - cron: '15 1,12 * * *'

env:
  COMPOSER_INSTALL_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  tests:
    name: PHP${{ matrix.php-version }} PgSQL${{ matrix.pgsql-version }} on ${{ matrix.os-version }}
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os-version:
          - ubuntu-22.04

        php-version:
          - "8.1"
          - "8.2"

        pgsql-version:
          - "14"
          - "15"

    services:
      postgres:
        image: postgres:${{ matrix.pgsql-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite, pdo_pgsql
          ini-values: date.timezone='UTC'

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer self-update -vvv
          composer install $COMPOSER_INSTALL_FLAGS

      - name: PHPUnit
        run: vendor/bin/phpunit --group pgsql --colors=always
