name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  COMPOSER_INSTALL_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  phpunit:
    name: PHP ${{ matrix.php-version }} mysql ${{ matrix.mysql-version }} on ${{ matrix.os-version }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os-version: [ubuntu-20.04, ubuntu-22.04]
        php-version: ['8.0', '8.1', '8.2']
        mysql-version: ['5.7', '8.0']

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Generate french locale
        run: sudo locale-gen fr_FR.UTF-8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite
          ini-values: date.timezone='UTC', session.save_path="${{ runner.temp }}"

      - name: Install Memcached
        uses: niden/actions-memcached@v7

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer install $COMPOSER_INSTALL_FLAGS

      - name: PHPUnit
        run: vendor/bin/phpunit --exclude-group mssql --verbose --colors=always
