name: phpstan

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  phpstan:
    name: PHP ${{ matrix.php-version }} on ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, 'phpstan ci') }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Deps
        run: |
          composer self-update -vvv
          composer redo-install

      - run: vendor/bin/phpstan --memory-limit=512M --debug
